services:
  web:
    image: odoo:18.0
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "127.0.0.1:8069:8069"
      - "127.0.0.1:8072:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons/addons
      - ./custom_addons:/mnt/extra-addons/custom_addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=${POSTGRES_PASS}
    networks:
      - odoo-net

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - odoo-net

networks:
  odoo-net:
    driver: bridge
    internal: true

volumes:
  odoo-web-data:
  odoo-db-data: